apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
    # useDockerCLI: true
  # googleCloudBuild:
  #   projectId: ticketing-dev-jpj
  artifacts:
    - image: jibujacob/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/nextjsclient
      context: nextjsclient
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: jibujacob/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/orders
      context: orders
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
