name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env: # Or as an environment variable
          credentials: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && npm install && npm run test:ci
